### ISSUE TITLE
screenBitmap.getBitmap()获取的bitmap直接保存的图片无内容

### ISSUE THREAD

**Issue by liuly0218** [MissMyDearBear/ScreenShotTools#1]
screenBitmap.getBitmap()获取的bitmap直接保存到本地SD卡，但是图片无内容
![a1562117371227](https://user-images.githubusercontent.com/23565012/60557193-1d509480-9d77-11e9-88cb-74b9eb392aef.jpg)

**Comment by MissMyDearBear** [comment]
你这个是截取的什么View，能发一下你是怎么使用的吗？

**Comment by MissMyDearBear** [comment]
> screenBitmap.getBitmap()获取的bitmap直接保存到本地SD卡，但是图片无内容
> ![a1562117371227](https://user-images.githubusercontent.com/23565012/60557193-1d509480-9d77-11e9-88cb-74b9eb392aef.jpg)

方便让我看看你是如何使用的吗？
